PIN_ROOT := pin-2.13-62732-gcc.4.4.7-linux
CONFIG_ROOT := $(PIN_ROOT)/source/tools/Config
TEST_TOOL_ROOTS := mtrace
include $(CONFIG_ROOT)/makefile.config
include $(TOOLS_ROOT)/Config/makefile.default.rules
